import { DAMAGE_TYPES, SEVERITY_LEVELS, SVG_VIEWS, DAMAGE_TYPE_LABELS, SEVERITY_LABELS } from '@rentapp/shared';
export { DAMAGE_TYPES, SEVERITY_LEVELS, SVG_VIEWS, DAMAGE_TYPE_LABELS, SEVERITY_LABELS };
