import { Test, TestingModule } from '@nestjs/testing';
import { INestApplication, ValidationPipe } from '@nestjs/common';
import request from 'supertest';
import * as argon2 from 'argon2';
import { AppModule } from '../src/app.module';
import { PrismaService } from '../src/prisma/prisma.service';
import { MailService } from '../src/mail/mail.service';
import { StorageService } from '../src/storage/storage.service';
import { PdfService } from '../src/contracts/pdf/pdf.service';
import { SmsService } from '../src/notifications/sms/sms.service';
import { UserRole, RentalStatus } from '@rentapp/shared';
import Redis from 'ioredis';

const ARGON2_OPTIONS = { memoryCost: 32768, timeCost: 3, parallelism: 1 };
const VALID_PESEL = '44051401359';

jest.setTimeout(30000);

// Valid 1x1 pixel JPEG buffer generated by Sharp
const testImageBuffer = Buffer.from(
  '/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSop' +
  'GR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgo' +
  'KCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAABAAEDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/' +
  'xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFQEBAQAAAAAAAAAAAAAAAAAABgj/xAAUEQEAAAAAAAAAAAAAAAAA' +
  'AAAA/9oADAMBAAIRAxEAPwCdABykX//Z',
  'base64',
);

describe('Damage Reports (e2e)', () => {
  let app: INestApplication;
  let prisma: PrismaService;
  let redis: Redis;
  let employeeToken: string;
  let mockMailService: Record<string, jest.Mock>;
  let mockStorageService: Record<string, jest.Mock>;
  let mockPdfService: Record<string, jest.Mock>;

  const adminEmail = 'dmg-admin@test.com';
  const adminPassword = 'DmgAdmin1!';
  const employeeEmail = 'dmg-employee@test.com';
  const employeePassword = 'DmgEmployee1!';
  const deviceId = '00000000-0000-4000-a000-000000000040';

  let rentalId: string;
  let walkthroughId: string;

  beforeAll(async () => {
    mockMailService = {
      sendSetupPasswordEmail: jest.fn(),
      sendResetPasswordEmail: jest.fn(),
      sendContractEmail: jest.fn().mockResolvedValue(undefined),
      sendAnnexEmail: jest.fn().mockResolvedValue(undefined),
    };

    mockStorageService = {
      onModuleInit: jest.fn(),
      upload: jest.fn().mockResolvedValue('mock-key'),
      getBuffer: jest.fn().mockResolvedValue(Buffer.from('mock-image-data')),
      getPresignedDownloadUrl: jest.fn().mockImplementation((key: string) =>
        Promise.resolve(`https://test-url/${key}`),
      ),
      delete: jest.fn().mockResolvedValue(undefined),
    };

    mockPdfService = {
      onModuleInit: jest.fn(),
      onModuleDestroy: jest.fn(),
      generateContractPdf: jest.fn().mockResolvedValue(Buffer.from('mock-pdf')),
      generateAnnexPdf: jest.fn().mockResolvedValue(Buffer.from('mock-annex-pdf')),
    };

    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    })
      .overrideProvider(MailService)
      .useValue(mockMailService)
      .overrideProvider(StorageService)
      .useValue(mockStorageService)
      .overrideProvider(PdfService)
      .useValue(mockPdfService)
      .overrideProvider(SmsService)
      .useValue({ normalizePhone: jest.fn((p: string) => p), send: jest.fn() })
      .compile();

    app = moduleFixture.createNestApplication();
    app.useGlobalPipes(
      new ValidationPipe({ whitelist: true, transform: true }),
    );
    await app.init();

    prisma = app.get(PrismaService);
    redis = new Redis(process.env.REDIS_URL!);

    // Force fresh DB connection to avoid stale cached plans after schema reset
    try { await prisma.$executeRawUnsafe('DEALLOCATE ALL'); } catch {}
    await prisma.$disconnect();
    await prisma.$connect();

    await redis.flushdb();

    // Clean up (full dependency order)
    await prisma.cepikVerification.deleteMany({});
    await prisma.inAppNotification.deleteMany({});
    await prisma.notification.deleteMany({});
    await prisma.damageReport.deleteMany({});
    await prisma.walkthroughPhoto.deleteMany({});
    await prisma.photoWalkthrough.deleteMany({});
    await prisma.contractSignature.deleteMany({});
    await prisma.contractAnnex.deleteMany({});
    await prisma.contract.deleteMany({});
    await prisma.rental.deleteMany({});
    await prisma.vehicleDocument.deleteMany({});
    await prisma.vehicleInsurance.deleteMany({});
    await prisma.vehicleInspection.deleteMany({});
    await prisma.vehicle.deleteMany({});
    await prisma.customer.deleteMany({});
    await prisma.auditLog.deleteMany({});
    await prisma.user.deleteMany({});

    // Seed admin
    const adminHash = await argon2.hash(adminPassword, ARGON2_OPTIONS);
    await prisma.user.create({
      data: {
        email: adminEmail,
        name: 'Damage Admin',
        role: UserRole.ADMIN,
        passwordHash: adminHash,
        isActive: true,
      },
    });

    // Seed employee
    const empHash = await argon2.hash(employeePassword, ARGON2_OPTIONS);
    await prisma.user.create({
      data: {
        email: employeeEmail,
        name: 'Damage Employee',
        role: UserRole.EMPLOYEE,
        passwordHash: empHash,
        isActive: true,
      },
    });

    // Login
    const adminRes = await request(app.getHttpServer())
      .post('/auth/login')
      .send({ email: adminEmail, password: adminPassword, deviceId });

    const empRes = await request(app.getHttpServer())
      .post('/auth/login')
      .send({
        email: employeeEmail,
        password: employeePassword,
        deviceId: '00000000-0000-4000-a000-000000000041',
      });
    employeeToken = empRes.body.accessToken;

    const adminToken = adminRes.body.accessToken;

    // Create vehicle
    const vRes = await request(app.getHttpServer())
      .post('/vehicles')
      .set('Authorization', `Bearer ${adminToken}`)
      .send({
        registration: 'DM12345',
        vin: 'WVWZZZ3CZWE500001',
        make: 'Toyota',
        model: 'Yaris',
        year: 2023,
        fuelType: 'PETROL',
        transmission: 'MANUAL',
        color: 'Black',
        mileage: 30000,
      })
      .expect(201);
    const vehicleId = vRes.body.id;

    // Create customer
    const cRes = await request(app.getHttpServer())
      .post('/customers')
      .set('Authorization', `Bearer ${adminToken}`)
      .send({
        firstName: 'Anna',
        lastName: 'Uszkodzona',
        phone: '+48123456770',
        email: 'anna-dmg@example.com',
        address: 'ul. Testowa 2, Krakow',
        pesel: VALID_PESEL,
        idNumber: 'DMG123456',
        licenseNumber: 'DRV770012',
        idIssuedBy: 'Urzad Miasta Krakow',
        idIssuedDate: '2019-06-01',
        licenseCategory: 'B',
        licenseIssuedBy: 'Starostwo Powiatowe',
      })
      .expect(201);
    const customerId = cRes.body.id;

    // Create rental
    const rRes = await request(app.getHttpServer())
      .post('/rentals')
      .set('Authorization', `Bearer ${adminToken}`)
      .send({
        vehicleId,
        customerId,
        startDate: '2026-03-01T00:00:00Z',
        endDate: '2026-03-15T00:00:00Z',
        dailyRateNet: 8000,
        totalPriceNet: 112000,
        vatRate: 23,
        status: RentalStatus.ACTIVE,
      })
      .expect(201);
    rentalId = rRes.body.id;

    // Create a walkthrough for damage reports
    const wtRes = await request(app.getHttpServer())
      .post('/walkthroughs')
      .set('Authorization', `Bearer ${employeeToken}`)
      .send({ rentalId, type: 'HANDOVER' })
      .expect(201);
    walkthroughId = wtRes.body.id;
  }, 60000);

  afterAll(async () => {
    await prisma.cepikVerification.deleteMany({});
    await prisma.inAppNotification.deleteMany({});
    await prisma.notification.deleteMany({});
    await prisma.damageReport.deleteMany({});
    await prisma.walkthroughPhoto.deleteMany({});
    await prisma.photoWalkthrough.deleteMany({});
    await prisma.contractSignature.deleteMany({});
    await prisma.contractAnnex.deleteMany({});
    await prisma.contract.deleteMany({});
    await prisma.rental.deleteMany({});
    await prisma.vehicleDocument.deleteMany({});
    await prisma.vehicleInsurance.deleteMany({});
    await prisma.vehicleInspection.deleteMany({});
    await prisma.vehicle.deleteMany({});
    await prisma.customer.deleteMany({});
    await prisma.auditLog.deleteMany({});
    await prisma.user.deleteMany({});
    await redis.flushdb();
    await redis.quit();
    await app.close();
  });

  it('POST /damage-reports creates a damage report', async () => {
    const res = await request(app.getHttpServer())
      .post('/damage-reports')
      .set('Authorization', `Bearer ${employeeToken}`)
      .send({
        walkthroughId,
        pins: [
          {
            pinNumber: 1,
            svgView: 'top',
            x: 50,
            y: 30,
            damageType: 'scratch',
            severity: 'minor',
            note: 'Small scratch on roof',
          },
        ],
      })
      .expect(201);

    expect(res.body.walkthroughId).toBe(walkthroughId);
    expect(res.body.pins).toBeDefined();
  });

  it('POST /damage-reports/:walkthroughId/pins adds a pin', async () => {
    const res = await request(app.getHttpServer())
      .post(`/damage-reports/${walkthroughId}/pins`)
      .set('Authorization', `Bearer ${employeeToken}`)
      .send({
        pinNumber: 2,
        svgView: 'front',
        x: 40,
        y: 60,
        damageType: 'dent',
        severity: 'moderate',
      })
      .expect(201);

    expect((res.body.pins as any[]).length).toBe(2);
  });

  it('DELETE /damage-reports/:walkthroughId/pins/:pinNumber removes a pin', async () => {
    const res = await request(app.getHttpServer())
      .delete(`/damage-reports/${walkthroughId}/pins/1`)
      .set('Authorization', `Bearer ${employeeToken}`)
      .expect(200);

    // After removing pin 1, pins are renumbered
    expect((res.body.pins as any[]).length).toBe(1);
    expect((res.body.pins as any[])[0].pinNumber).toBe(1); // renumbered
  });

  it('POST /damage-reports/:walkthroughId/no-damage rejects when pins exist', async () => {
    await request(app.getHttpServer())
      .post(`/damage-reports/${walkthroughId}/no-damage`)
      .set('Authorization', `Bearer ${employeeToken}`)
      .expect(400);
  });

  it('GET /damage-reports/walkthrough/:walkthroughId returns damage report', async () => {
    const res = await request(app.getHttpServer())
      .get(`/damage-reports/walkthrough/${walkthroughId}`)
      .set('Authorization', `Bearer ${employeeToken}`)
      .expect(200);

    expect(res.body.walkthroughId).toBe(walkthroughId);
    expect(res.body.pins).toBeDefined();
  });

  it('GET /damage-reports/comparison/:rentalId returns comparison', async () => {
    const res = await request(app.getHttpServer())
      .get(`/damage-reports/comparison/${rentalId}`)
      .set('Authorization', `Bearer ${employeeToken}`)
      .expect(200);

    expect(res.body).toHaveProperty('handoverPins');
    expect(res.body).toHaveProperty('returnPins');
    expect(res.body).toHaveProperty('newPins');
  });

  it('rejects damage report with invalid pin coordinates (x > 100)', async () => {
    // Create a second walkthrough so we can test a fresh damage report
    const wtRes = await request(app.getHttpServer())
      .post('/walkthroughs')
      .set('Authorization', `Bearer ${employeeToken}`)
      .send({ rentalId, type: 'RETURN' })
      .expect(201);

    await request(app.getHttpServer())
      .post('/damage-reports')
      .set('Authorization', `Bearer ${employeeToken}`)
      .send({
        walkthroughId: wtRes.body.id,
        pins: [
          {
            pinNumber: 1,
            svgView: 'top',
            x: 150,
            y: 30,
            damageType: 'scratch',
            severity: 'minor',
          },
        ],
      })
      .expect(400);
  });
});
