import { Test, TestingModule } from '@nestjs/testing';
import { INestApplication, ValidationPipe } from '@nestjs/common';
import request from 'supertest';
import * as argon2 from 'argon2';
import { AppModule } from '../src/app.module';
import { PrismaService } from '../src/prisma/prisma.service';
import { MailService } from '../src/mail/mail.service';
import { StorageService } from '../src/storage/storage.service';
import { PdfService } from '../src/contracts/pdf/pdf.service';
import { UserRole, RentalStatus } from '@rentapp/shared';
import Redis from 'ioredis';

const ARGON2_OPTIONS = { memoryCost: 32768, timeCost: 3, parallelism: 1 };
const VALID_PESEL = '44051401359';

// Valid 1x1 pixel JPEG buffer generated by Sharp
const testImageBuffer = Buffer.from(
  '/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSop' +
  'GR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgo' +
  'KCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAABAAEDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/' +
  'xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFQEBAQAAAAAAAAAAAAAAAAAABgj/xAAUEQEAAAAAAAAAAAAAAAAA' +
  'AAAA/9oADAMBAAIRAxEAPwCdABykX//Z',
  'base64',
);

describe('Photo Walkthrough (e2e)', () => {
  let app: INestApplication;
  let prisma: PrismaService;
  let redis: Redis;
  let adminToken: string;
  let employeeToken: string;
  let customerToken: string;
  let mockMailService: Record<string, jest.Mock>;
  let mockStorageService: Record<string, jest.Mock>;
  let mockPdfService: Record<string, jest.Mock>;

  const adminEmail = 'photo-admin@test.com';
  const adminPassword = 'PhotoAdmin1!';
  const employeeEmail = 'photo-employee@test.com';
  const employeePassword = 'PhotoEmployee1!';
  const customerEmail = 'photo-customer@test.com';
  const customerPassword = 'PhotoCustomer1!';
  const deviceId = '00000000-0000-4000-a000-000000000030';

  let rentalId: string;
  let walkthroughId: string;

  beforeAll(async () => {
    mockMailService = {
      sendSetupPasswordEmail: jest.fn(),
      sendResetPasswordEmail: jest.fn(),
      sendContractEmail: jest.fn().mockResolvedValue(undefined),
      sendAnnexEmail: jest.fn().mockResolvedValue(undefined),
    };

    mockStorageService = {
      onModuleInit: jest.fn(),
      upload: jest.fn().mockResolvedValue('mock-key'),
      getBuffer: jest.fn().mockResolvedValue(Buffer.from('mock-image-data')),
      getPresignedDownloadUrl: jest.fn().mockImplementation((key: string) =>
        Promise.resolve(`https://test-url/${key}`),
      ),
      delete: jest.fn().mockResolvedValue(undefined),
    };

    mockPdfService = {
      onModuleInit: jest.fn(),
      onModuleDestroy: jest.fn(),
      generateContractPdf: jest.fn().mockResolvedValue(Buffer.from('mock-pdf')),
      generateAnnexPdf: jest.fn().mockResolvedValue(Buffer.from('mock-annex-pdf')),
    };

    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    })
      .overrideProvider(MailService)
      .useValue(mockMailService)
      .overrideProvider(StorageService)
      .useValue(mockStorageService)
      .overrideProvider(PdfService)
      .useValue(mockPdfService)
      .compile();

    app = moduleFixture.createNestApplication();
    app.useGlobalPipes(
      new ValidationPipe({ whitelist: true, transform: true }),
    );
    await app.init();

    prisma = app.get(PrismaService);
    redis = new Redis(process.env.REDIS_URL!);
    await redis.flushdb();

    // Clean up from previous runs (order matters for FK constraints)
    await prisma.damageReport.deleteMany({});
    await prisma.walkthroughPhoto.deleteMany({});
    await prisma.photoWalkthrough.deleteMany({});
    await prisma.contractSignature.deleteMany({});
    await prisma.contractAnnex.deleteMany({});
    await prisma.contract.deleteMany({});
    await prisma.rental.deleteMany({});
    await prisma.vehicleDocument.deleteMany({});
    await prisma.vehicleInsurance.deleteMany({});
    await prisma.vehicleInspection.deleteMany({});
    await prisma.vehicle.deleteMany({});
    await prisma.customer.deleteMany({});
    await prisma.auditLog.deleteMany({});
    await prisma.user.deleteMany({});

    // Seed admin user
    const adminHash = await argon2.hash(adminPassword, ARGON2_OPTIONS);
    await prisma.user.create({
      data: {
        email: adminEmail,
        name: 'Photo Admin',
        role: UserRole.ADMIN,
        passwordHash: adminHash,
        isActive: true,
      },
    });

    // Seed employee user
    const empHash = await argon2.hash(employeePassword, ARGON2_OPTIONS);
    await prisma.user.create({
      data: {
        email: employeeEmail,
        name: 'Photo Employee',
        role: UserRole.EMPLOYEE,
        passwordHash: empHash,
        isActive: true,
      },
    });

    // Seed customer user (for role rejection test)
    const custHash = await argon2.hash(customerPassword, ARGON2_OPTIONS);
    await prisma.user.create({
      data: {
        email: customerEmail,
        name: 'Photo Customer',
        role: UserRole.CUSTOMER,
        passwordHash: custHash,
        isActive: true,
      },
    });

    // Login all three
    const adminRes = await request(app.getHttpServer())
      .post('/auth/login')
      .send({ email: adminEmail, password: adminPassword, deviceId });
    adminToken = adminRes.body.accessToken;

    const empRes = await request(app.getHttpServer())
      .post('/auth/login')
      .send({
        email: employeeEmail,
        password: employeePassword,
        deviceId: '00000000-0000-4000-a000-000000000031',
      });
    employeeToken = empRes.body.accessToken;

    const custRes = await request(app.getHttpServer())
      .post('/auth/login')
      .send({
        email: customerEmail,
        password: customerPassword,
        deviceId: '00000000-0000-4000-a000-000000000032',
      });
    customerToken = custRes.body.accessToken;

    // Create vehicle
    const vRes = await request(app.getHttpServer())
      .post('/vehicles')
      .set('Authorization', `Bearer ${adminToken}`)
      .send({
        registration: 'PH12345',
        vin: 'WVWZZZ3CZWE400001',
        make: 'Toyota',
        model: 'Corolla',
        year: 2023,
        fuelType: 'PETROL',
        transmission: 'AUTOMATIC',
        color: 'White',
        mileage: 50000,
      })
      .expect(201);
    const vehicleId = vRes.body.id;

    // Create customer
    const cRes = await request(app.getHttpServer())
      .post('/customers')
      .set('Authorization', `Bearer ${adminToken}`)
      .send({
        firstName: 'Jan',
        lastName: 'Fotografik',
        phone: '+48123456780',
        email: 'jan-photo@example.com',
        address: 'ul. Testowa 1, Warszawa',
        pesel: VALID_PESEL,
        idNumber: 'PHO123456',
        licenseNumber: 'DRV780012',
        idIssuedBy: 'Urzad Miasta Warszawa',
        idIssuedDate: '2020-01-15',
        licenseCategory: 'B',
        licenseIssuedBy: 'Starostwo Powiatowe',
      })
      .expect(201);
    const customerId = cRes.body.id;

    // Create active rental
    const rRes = await request(app.getHttpServer())
      .post('/rentals')
      .set('Authorization', `Bearer ${adminToken}`)
      .send({
        vehicleId,
        customerId,
        startDate: '2026-03-01T00:00:00Z',
        endDate: '2026-03-10T00:00:00Z',
        dailyRateNet: 10000,
        totalPriceNet: 90000,
        vatRate: 23,
        status: RentalStatus.ACTIVE,
      })
      .expect(201);
    rentalId = rRes.body.id;
  }, 60000);

  afterAll(async () => {
    await prisma.damageReport.deleteMany({});
    await prisma.walkthroughPhoto.deleteMany({});
    await prisma.photoWalkthrough.deleteMany({});
    await prisma.contractSignature.deleteMany({});
    await prisma.contractAnnex.deleteMany({});
    await prisma.contract.deleteMany({});
    await prisma.rental.deleteMany({});
    await prisma.vehicleDocument.deleteMany({});
    await prisma.vehicleInsurance.deleteMany({});
    await prisma.vehicleInspection.deleteMany({});
    await prisma.vehicle.deleteMany({});
    await prisma.customer.deleteMany({});
    await prisma.auditLog.deleteMany({});
    await prisma.user.deleteMany({});
    await redis.flushdb();
    await redis.quit();
    await app.close();
  });

  it('POST /walkthroughs creates a HANDOVER walkthrough', async () => {
    const res = await request(app.getHttpServer())
      .post('/walkthroughs')
      .set('Authorization', `Bearer ${employeeToken}`)
      .send({ rentalId, type: 'HANDOVER' })
      .expect(201);

    expect(res.body.rentalId).toBe(rentalId);
    expect(res.body.type).toBe('HANDOVER');
    expect(res.body.id).toBeDefined();
    walkthroughId = res.body.id;
  });

  it('POST /walkthroughs/:id/photos uploads a photo for a position', async () => {
    const res = await request(app.getHttpServer())
      .post(`/walkthroughs/${walkthroughId}/photos`)
      .set('Authorization', `Bearer ${employeeToken}`)
      .attach('file', testImageBuffer, { filename: 'front.jpg', contentType: 'image/jpeg' })
      .field('position', 'front')
      .field('capturedAt', new Date().toISOString())
      .expect(201);

    expect(res.body.position).toBe('front');
    expect(res.body.photoKey).toContain('photos/');
  });

  it('POST /walkthroughs/:id/submit rejects incomplete walkthrough', async () => {
    // Only 1 photo uploaded, need all 8 positions
    await request(app.getHttpServer())
      .post(`/walkthroughs/${walkthroughId}/submit`)
      .set('Authorization', `Bearer ${employeeToken}`)
      .expect(400);
  });

  it('POST /walkthroughs/:id/submit succeeds with all 8 positions', async () => {
    // Upload remaining 7 positions
    const remaining = [
      'rear', 'left_side', 'right_side',
      'interior_front', 'interior_rear', 'dashboard', 'trunk',
    ];

    for (const pos of remaining) {
      await request(app.getHttpServer())
        .post(`/walkthroughs/${walkthroughId}/photos`)
        .set('Authorization', `Bearer ${employeeToken}`)
        .attach('file', testImageBuffer, { filename: `${pos}.jpg`, contentType: 'image/jpeg' })
        .field('position', pos)
        .field('capturedAt', new Date().toISOString())
        .expect(201);
    }

    const res = await request(app.getHttpServer())
      .post(`/walkthroughs/${walkthroughId}/submit`)
      .set('Authorization', `Bearer ${employeeToken}`)
      .expect(201);

    expect(res.body.submittedAt).toBeDefined();
  });

  it('GET /walkthroughs/:id returns walkthrough with photos', async () => {
    const res = await request(app.getHttpServer())
      .get(`/walkthroughs/${walkthroughId}`)
      .set('Authorization', `Bearer ${employeeToken}`)
      .expect(200);

    expect(res.body.id).toBe(walkthroughId);
    expect(res.body.photos).toBeDefined();
    expect(Array.isArray(res.body.photos)).toBe(true);
    expect(res.body.photos.length).toBe(8);
  });

  it('GET /walkthroughs/rentals/:rentalId/comparison returns comparison data', async () => {
    const res = await request(app.getHttpServer())
      .get(`/walkthroughs/rentals/${rentalId}/comparison`)
      .set('Authorization', `Bearer ${employeeToken}`)
      .expect(200);

    expect(Array.isArray(res.body)).toBe(true);
    // Should have pairs for each position in the handover walkthrough
    expect(res.body.length).toBeGreaterThan(0);
    expect(res.body[0]).toHaveProperty('position');
    expect(res.body[0]).toHaveProperty('handover');
    expect(res.body[0]).toHaveProperty('return');
  });

  it('PUT /walkthroughs/:id/photos/:position replaces photo within edit window', async () => {
    const res = await request(app.getHttpServer())
      .put(`/walkthroughs/${walkthroughId}/photos/front`)
      .set('Authorization', `Bearer ${employeeToken}`)
      .attach('file', testImageBuffer, { filename: 'front_new.jpg', contentType: 'image/jpeg' })
      .field('position', 'front')
      .field('capturedAt', new Date().toISOString())
      .expect(200);

    expect(res.body.position).toBe('front');
  });

  it('rejects CUSTOMER role access', async () => {
    await request(app.getHttpServer())
      .post('/walkthroughs')
      .set('Authorization', `Bearer ${customerToken}`)
      .send({ rentalId, type: 'RETURN' })
      .expect(403);
  });

  it('rejects photo upload for non-existent walkthrough', async () => {
    await request(app.getHttpServer())
      .post('/walkthroughs/00000000-0000-4000-a000-000000000099/photos')
      .set('Authorization', `Bearer ${employeeToken}`)
      .attach('file', testImageBuffer, { filename: 'front.jpg', contentType: 'image/jpeg' })
      .field('position', 'front')
      .field('capturedAt', new Date().toISOString())
      .expect(404);
  });
});
